# Generated by Django 2.1.5 on 2019-03-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190317_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=25, null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
       
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Cliente', to_field='cedula'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Opciones', to_field='valor_iva'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.IntegerField(null=True),
        ),
        
    ]
